# Generated by Django 4.0 on 2021-12-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_on_post_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
